# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lottie-Example-Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lottie-Example-Swift
  pod 'lottie-ios', :path => '../'
  
  target 'Lottie-Example-SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Lottie-Example-SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
