// Created by Cal Stephens on 12/20/21.
// Copyright © 2021 Airbnb Inc. All rights reserved.

// Carthage support requires a shared framework scheme,
// which is not generated by SPM.
//
// To support Carthage, we have a `LottieCarthage` framework scheme
// that @_exported imports the `Lottie` SPM package.
@_exported import Lottie
