# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lottie-Screenshot' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Lottie-Screenshot

  target 'Lottie-ScreenshotTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'FBSnapshotTestCase/Core'
    pod 'lottie-ios', :path => '../'
  end

end
